"""Current-main camera parameter types and pure-JAX kernel operations."""

from ._projection_validate import validate_camera_projection
from .ops import (
    camera_rays_to_image_points,
    generate_image_points,
    image_points_to_camera_rays,
    image_points_to_world_rays_shutter_pose,
    image_points_to_world_rays_static_pose,
    interpolate_dynamic_pose,
    mean_pose_to_static_pose,
    pixel_grid_to_world_rays_shutter_pose,
    project_world_points_mean_pose,
    project_world_points_shutter_pose,
    relative_frame_times,
    unpack_dynamic_pose_components,
)
from .types import (
    FISHEYE_MAX_FORWARD_POLY_TERMS,
    FTHETA_MAX_POLYNOMIAL_TERMS,
    REGISTERED_CAMERA_PROJECTIONS,
    REGISTERED_DISTORTIONS,
    BivariateWindshieldDistortion,
    CameraProjection,
    ExternalDistortion,
    FThetaProjection,
    NoExternalDistortion,
    OpenCVFisheyeProjection,
    OpenCVPinholeProjection,
    ReferencePolynomial,
    ShutterType,
)
from .windshield import (
    MAX_H_POLYNOMIAL_TERMS,
    MAX_V_POLYNOMIAL_TERMS,
    from_components,
)

__all__ = [  # noqa: RUF022 - preserve the public compatibility order
    "BivariateWindshieldDistortion",
    "CameraProjection",
    "ExternalDistortion",
    "FISHEYE_MAX_FORWARD_POLY_TERMS",
    "FTHETA_MAX_POLYNOMIAL_TERMS",
    "FThetaProjection",
    "MAX_H_POLYNOMIAL_TERMS",
    "MAX_V_POLYNOMIAL_TERMS",
    "NoExternalDistortion",
    "OpenCVFisheyeProjection",
    "OpenCVPinholeProjection",
    "ReferencePolynomial",
    "REGISTERED_CAMERA_PROJECTIONS",
    "REGISTERED_DISTORTIONS",
    "ShutterType",
    "camera_rays_to_image_points",
    "from_components",
    "generate_image_points",
    "image_points_to_camera_rays",
    "image_points_to_world_rays_static_pose",
    "image_points_to_world_rays_shutter_pose",
    "interpolate_dynamic_pose",
    "mean_pose_to_static_pose",
    "pixel_grid_to_world_rays_shutter_pose",
    "project_world_points_mean_pose",
    "project_world_points_shutter_pose",
    "relative_frame_times",
    "unpack_dynamic_pose_components",
    "validate_camera_projection",
]
