"""Public geometry API: quaternion, pose, and trajectory operators."""

from .pose import (
    frame_transform_poses_tquat,
    se3_interpolate_tracks,
    se3pose_compose,
    se3pose_from_matrix,
    se3pose_inverse_transform_direction,
    se3pose_inverse_transform_point,
    se3pose_to_inverse_matrix,
    se3pose_to_matrix,
    se3pose_transform_direction,
    se3pose_transform_point,
    trajectory_get_rotation_2poses,
    trajectory_transform_point_1pose,
    trajectory_transform_point_2poses,
)
from .quaternion import (
    quat_angular_distance,
    quat_conjugate,
    quat_from_axis_angle,
    quat_identity,
    quat_inverse,
    quat_lerp,
    quat_manifold_interp,
    quat_multiply,
    quat_normalize_safe,
    quat_rotate_vector,
    quat_slerp,
    quat_to_matrix,
)

__all__ = [
    "frame_transform_poses_tquat",
    "se3_interpolate_tracks",
    "se3pose_compose",
    "se3pose_from_matrix",
    "se3pose_inverse_transform_direction",
    "se3pose_inverse_transform_point",
    "se3pose_to_inverse_matrix",
    "se3pose_to_matrix",
    "se3pose_transform_direction",
    "se3pose_transform_point",
    "trajectory_get_rotation_2poses",
    "trajectory_transform_point_1pose",
    "trajectory_transform_point_2poses",
    "quat_angular_distance",
    "quat_conjugate",
    "quat_from_axis_angle",
    "quat_identity",
    "quat_inverse",
    "quat_lerp",
    "quat_manifold_interp",
    "quat_multiply",
    "quat_normalize_safe",
    "quat_rotate_vector",
    "quat_slerp",
    "quat_to_matrix",
]
